name: Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - .github/workflows/docs.yml

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Set Up Poetry
        run: pipx install poetry==1.3.2

      - name: Save Cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Build Documentation
        run: poetry install --only docs && poetry run mkdocs build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Documentation
        uses: actions/deploy-pages@v1
