name: Publish Pekora

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Publish to PyPI
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.11.1
          poetry-version: 1.3.2
          build: true
          token: ${{ secrets.PYPI_TOKEN }}

  brew-build:
    name: Build Homebrew Formula
    runs-on: ubuntu-latest
    needs: pypi

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Set Up Poetry
        run: pipx install poetry==1.3.2

      - name: Build Formula
        run: poetry self add poetry-brew && poetry brew

      - name: Upload Formula
        uses: actions/upload-artifact@v3
        with:
          name: pekora.rb
          path: pekora.rb

  brew-publish:
    name: Publish Homebrew Formula
    runs-on: ubuntu-latest
    needs: brew-build

    steps:
      - name: Download Formula
        uses: actions/download-artifact@v3
        with:
          name: pekora.rb
          path: .

      - name: Publish to Houkago Tea Tap
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HTT_TOKEN }}
        with:
          source_file: pekora.rb
          destination_repo: celsiusnarhwal/homebrew-htt
          destination_folder: Formula
          commit_message: "Update formula for Pekora https://github.com/celsiusnarhwal/pekora"
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
